server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bear?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT8%2B
    username: root
    password: gm211318
