server:
  port: 8080
  servlet:
    context-path: /user
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bear?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: gm211318

  main:
    allow-circular-references: true
